"""Add DigitalHuman models

Revision ID: 3c7a2a5f52db
Revises: cb994cbbc240
Create Date: 2026-06-17 19:08:45.261198
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c7a2a5f52db'
down_revision: Union[str, None] = 'cb994cbbc240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_clones',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('heygen_avatar_id', sa.String(), nullable=False),
    sa.Column('heygen_group_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_clones_deleted_at'), 'avatar_clones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_avatar_clones_id'), 'avatar_clones', ['id'], unique=False)
    op.create_table('voice_clones',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('elevenlabs_voice_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_clones_deleted_at'), 'voice_clones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_voice_clones_id'), 'voice_clones', ['id'], unique=False)
    op.create_table('digital_humans',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('voice_tone', sa.String(), nullable=False),
    sa.Column('accent', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voice_clone_id', sa.UUID(), nullable=False),
    sa.Column('avatar_clone_id', sa.UUID(), nullable=False),
    sa.Column('preview_video_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['avatar_clone_id'], ['avatar_clones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_clone_id'], ['voice_clones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_humans_deleted_at'), 'digital_humans', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_digital_humans_id'), 'digital_humans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_humans_id'), table_name='digital_humans')
    op.drop_index(op.f('ix_digital_humans_deleted_at'), table_name='digital_humans')
    op.drop_table('digital_humans')
    op.drop_index(op.f('ix_voice_clones_id'), table_name='voice_clones')
    op.drop_index(op.f('ix_voice_clones_deleted_at'), table_name='voice_clones')
    op.drop_table('voice_clones')
    op.drop_index(op.f('ix_avatar_clones_id'), table_name='avatar_clones')
    op.drop_index(op.f('ix_avatar_clones_deleted_at'), table_name='avatar_clones')
    op.drop_table('avatar_clones')
    # ### end Alembic commands ###
