"""add_ai_preferences_and_pipeline_runs

Revision ID: 470308585a64
Revises: 2557c7006d83
Create Date: 2026-06-15 13:29:57.783868
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '470308585a64'
down_revision: Union[str, None] = '2557c7006d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_provider', sa.String(length=50), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('fallback_enabled', sa.Boolean(), nullable=False),
    sa.Column('fallback_action', sa.String(length=20), nullable=False),
    sa.Column('fallback_provider', sa.String(length=50), nullable=True),
    sa.Column('fallback_model', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('provider_keys_encrypted', sa.Text(), nullable=True),
    sa.Column('task_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_preferences_deleted_at'), 'ai_preferences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_preferences_id'), 'ai_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_ai_preferences_user_id'), 'ai_preferences', ['user_id'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_variation', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_deleted_at'), 'pipeline_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_project_id'), 'pipeline_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_stage'), 'pipeline_runs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_stage'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_project_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_deleted_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_ai_preferences_user_id'), table_name='ai_preferences')
    op.drop_index(op.f('ix_ai_preferences_id'), table_name='ai_preferences')
    op.drop_index(op.f('ix_ai_preferences_deleted_at'), table_name='ai_preferences')
    op.drop_table('ai_preferences')
    # ### end Alembic commands ###
