"""Rename voice id to heygen

Revision ID: 7aeec9c6d1dd
Revises: 3c7a2a5f52db
Create Date: 2026-06-17 19:42:00.451858
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7aeec9c6d1dd'
down_revision: Union[str, None] = '3c7a2a5f52db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('voice_clones', sa.Column('heygen_voice_id', sa.String(), nullable=False))
    op.drop_column('voice_clones', 'elevenlabs_voice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_clones', sa.Column('elevenlabs_voice_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('voice_clones', 'heygen_voice_id')
    # ### end Alembic commands ###
