"""Add AvatarAsset model

Revision ID: cb994cbbc240
Revises: 0e66a3d3cb8c
Create Date: 2026-06-16 09:45:47.234003
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb994cbbc240'
down_revision: Union[str, None] = '0e66a3d3cb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_assets',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('heygen_avatar_id', sa.String(), nullable=True),
    sa.Column('heygen_group_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_type', sa.String(), nullable=False),
    sa.Column('preview_image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_assets_deleted_at'), 'avatar_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_avatar_assets_id'), 'avatar_assets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_avatar_assets_id'), table_name='avatar_assets')
    op.drop_index(op.f('ix_avatar_assets_deleted_at'), table_name='avatar_assets')
    op.drop_table('avatar_assets')
    # ### end Alembic commands ###
